// This file is automatically generated - do not directly modify.

#pragma once

#include "HDFException.h"

namespace HDF5DotNet
{ 
   ///<summary>
   /// H5Dcreate throws this exception on any error condition.
   ///</summary>
   public ref class H5DcreateException : public HDFException
   {
     internal:
        H5DcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Dopen throws this exception on any error condition.
   ///</summary>
   public ref class H5DopenException : public HDFException
   {
     internal:
        H5DopenException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Dclose throws this exception on any error condition.
   ///</summary>
   public ref class H5DcloseException : public HDFException
   {
     internal:
        H5DcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Dread throws this exception on any error condition.
   ///</summary>
   public ref class H5DreadException : public HDFException
   {
     internal:
        H5DreadException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Dwrite throws this exception on any error condition.
   ///</summary>
   public ref class H5DwriteException : public HDFException
   {
     internal:
        H5DwriteException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DgetSpace throws this exception on any error condition.
   ///</summary>
   public ref class H5DgetSpaceException : public HDFException
   {
     internal:
        H5DgetSpaceException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DgetType throws this exception on any error condition.
   ///</summary>
   public ref class H5DgetTypeException : public HDFException
   {
     internal:
        H5DgetTypeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DsetExtend throws this exception on any error condition.
   ///</summary>
   public ref class H5DsetExtentException : public HDFException
   {
     internal:
        H5DsetExtentException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Fcreate throws this exception on any error condition.
   ///</summary>
   public ref class H5FcreateException : public HDFException
   {
     internal:
        H5FcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Fclose throws this exception on any error condition.
   ///</summary>
   public ref class H5FcloseException : public HDFException
   {
     internal:
        H5FcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Fopen throws this exception on any error condition.
   ///</summary>
   public ref class H5FopenException : public HDFException
   {
     internal:
        H5FopenException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Gcreate throws this exception on any error condition.
   ///</summary>
   public ref class H5GcreateException : public HDFException
   {
     internal:
        H5GcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Gopen throws this exception on any error condition.
   ///</summary>
   public ref class H5GopenException : public HDFException
   {
     internal:
        H5GopenException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GgetObjInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5GgetObjInfoException : public HDFException
   {
     internal:
        H5GgetObjInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GIterate throws this exception on any error condition.
   ///</summary>
   public ref class H5GIterateException : public HDFException
   {
     internal:
        H5GIterateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Gclose throws this exception on any error condition.
   ///</summary>
   public ref class H5GcloseException : public HDFException
   {
     internal:
        H5GcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5ScreateSimple throws this exception on any error condition.
   ///</summary>
   public ref class H5ScreateSimpleException : public HDFException
   {
     internal:
        H5ScreateSimpleException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Screate throws this exception on any error condition.
   ///</summary>
   public ref class H5ScreateException : public HDFException
   {
     internal:
        H5ScreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SgetSimpleExtentDims throws this exception on any error condition.
   ///</summary>
   public ref class H5SgetSimpleExtentDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentDimsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Sclose throws this exception on any error condition.
   ///</summary>
   public ref class H5ScloseException : public HDFException
   {
     internal:
        H5ScloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Tcopy throws this exception on any error condition.
   ///</summary>
   public ref class H5TcopyException : public HDFException
   {
     internal:
        H5TcopyException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TsetSize throws this exception on any error condition.
   ///</summary>
   public ref class H5TsetSizeException : public HDFException
   {
     internal:
        H5TsetSizeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Tclose throws this exception on any error condition.
   ///</summary>
   public ref class H5TcloseException : public HDFException
   {
     internal:
        H5TcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetSize throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetSizeException : public HDFException
   {
     internal:
        H5TgetSizeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TsetOrder throws this exception on any error condition.
   ///</summary>
   public ref class H5TsetOrderException : public HDFException
   {
     internal:
        H5TsetOrderException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Topen throws this exception on any error condition.
   ///</summary>
   public ref class H5TopenException : public HDFException
   {
     internal:
        H5TopenException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Tinsert throws this exception on any error condition.
   ///</summary>
   public ref class H5TinsertException : public HDFException
   {
     internal:
        H5TinsertException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TenumCreate throws this exception on any error condition.
   ///</summary>
   public ref class H5TenumCreateException : public HDFException
   {
     internal:
        H5TenumCreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TenumInsert throws this exception on any error condition.
   ///</summary>
   public ref class H5TenumInsertException : public HDFException
   {
     internal:
        H5TenumInsertException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetNativeType throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetNativeTypeException : public HDFException
   {
     internal:
        H5TgetNativeTypeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TvlenCreate throws this exception on any error condition.
   ///</summary>
   public ref class H5TvlenCreateException : public HDFException
   {
     internal:
        H5TvlenCreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetClass throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetClassException : public HDFException
   {
     internal:
        H5TgetClassException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetSign throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetSignException : public HDFException
   {
     internal:
        H5TgetSignException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberName throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberNameException : public HDFException
   {
     internal:
        H5TgetMemberNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberClass throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberClassException : public HDFException
   {
     internal:
        H5TgetMemberClassException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberIndexException : public HDFException
   {
     internal:
        H5TgetMemberIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberType throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberTypeException : public HDFException
   {
     internal:
        H5TgetMemberTypeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Tcreate throws this exception on any error condition.
   ///</summary>
   public ref class H5TcreateException : public HDFException
   {
     internal:
        H5TcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetNMembers throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetNMembersException : public HDFException
   {
     internal:
        H5TgetNMembersException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SselectStridedHyperslab throws this exception on any error condition.
   ///</summary>
   public ref class H5SselectStridedHyperslabException : public HDFException
   {
     internal:
        H5SselectStridedHyperslabException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SselectHyperslab throws this exception on any error condition.
   ///</summary>
   public ref class H5SselectHyperslabException : public HDFException
   {
     internal:
        H5SselectHyperslabException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SgetSimpleExtentMaxDims throws this exception on any error condition.
   ///</summary>
   public ref class H5SgetSimpleExtentMaxDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentMaxDimsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SgetSimpleExtentNDims throws this exception on any error condition.
   ///</summary>
   public ref class H5SgetSimpleExtentNDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentNDimsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SgetSimpleExtentNPoints throws this exception on any error condition.
   ///</summary>
   public ref class H5SgetSimpleExtentNPointsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentNPointsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5SselectNone throws this exception on any error condition.
   ///</summary>
   public ref class H5SselectNoneException : public HDFException
   {
     internal:
        H5SselectNoneException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GgetNumObjects throws this exception on any error condition.
   ///</summary>
   public ref class H5GgetNumObjectsException : public HDFException
   {
     internal:
        H5GgetNumObjectsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GgetObjectNameByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5GgetObjectNameByIndexException : public HDFException
   {
     internal:
        H5GgetObjectNameByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5EsuppressPrinting throws this exception on any error condition.
   ///</summary>
   public ref class H5EsuppressPrintingException : public HDFException
   {
     internal:
        H5EsuppressPrintingException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Tcommit throws this exception on any error condition.
   ///</summary>
   public ref class H5TcommitException : public HDFException
   {
     internal:
        H5TcommitException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Acreate throws this exception on any error condition.
   ///</summary>
   public ref class H5AcreateException : public HDFException
   {
     internal:
        H5AcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Awrite throws this exception on any error condition.
   ///</summary>
   public ref class H5AwriteException : public HDFException
   {
     internal:
        H5AwriteException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Aread throws this exception on any error condition.
   ///</summary>
   public ref class H5AreadException : public HDFException
   {
     internal:
        H5AreadException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Aclose throws this exception on any error condition.
   ///</summary>
   public ref class H5AcloseException : public HDFException
   {
     internal:
        H5AcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetName throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetNameException : public HDFException
   {
     internal:
        H5AgetNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AopenName throws this exception on any error condition.
   ///</summary>
   public ref class H5AopenNameException : public HDFException
   {
     internal:
        H5AopenNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetSpace throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetSpaceException : public HDFException
   {
     internal:
        H5AgetSpaceException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetType throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetTypeException : public HDFException
   {
     internal:
        H5AgetTypeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetNumberOfAttributes throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetNumberOfAttributesException : public HDFException
   {
     internal:
        H5AgetNumberOfAttributesException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Aiterate throws this exception on any error condition.
   ///</summary>
   public ref class H5AiterateException : public HDFException
   {
     internal:
        H5AiterateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5ADelete throws this exception on any error condition.
   ///</summary>
   public ref class H5ADeleteException : public HDFException
   {
     internal:
        H5ADeleteException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Pcreate throws this exception on any error condition.
   ///</summary>
   public ref class H5PcreateException : public HDFException
   {
     internal:
        H5PcreateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Pclose throws this exception on any error condition.
   ///</summary>
   public ref class H5PcloseException : public HDFException
   {
     internal:
        H5PcloseException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PsetChunk throws this exception on any error condition.
   ///</summary>
   public ref class H5PgetChunkException : public HDFException
   {
     internal:
        H5PgetChunkException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PsetChunk throws this exception on any error condition.
   ///</summary>
   public ref class H5PsetChunkException : public HDFException
   {
     internal:
        H5PsetChunkException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PsetDeflate throws this exception on any error condition.
   ///</summary>
   public ref class H5PsetDeflateException : public HDFException
   {
     internal:
        H5PsetDeflateException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PgetLayout throws this exception on any error condition.
   ///</summary>
   public ref class H5PgetLayoutException : public HDFException
   {
     internal:
        H5PgetLayoutException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TisVariableString throws this exception on any error condition.
   ///</summary>
   public ref class H5TisVariableStringException : public HDFException
   {
     internal:
        H5TisVariableStringException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5OgetInfoByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5OgetInfoByIndexException : public HDFException
   {
     internal:
        H5OgetInfoByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5LgetInfoByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5LgetInfoByIndexException : public HDFException
   {
     internal:
        H5LgetInfoByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetNameByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetNameByIndexException : public HDFException
   {
     internal:
        H5AgetNameByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AopenIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5AopenIndexException : public HDFException
   {
     internal:
        H5AopenIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AopenByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5AopenByIndexException : public HDFException
   {
     internal:
        H5AopenByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AgetInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5AgetInfoException : public HDFException
   {
     internal:
        H5AgetInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5OgetInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5OgetInfoException : public HDFException
   {
     internal:
        H5OgetInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GgetInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5GgetInfoException : public HDFException
   {
     internal:
        H5GgetInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5LgetNameByIndex throws this exception on any error condition.
   ///</summary>
   public ref class H5LgetNameByIndexException : public HDFException
   {
     internal:
        H5LgetNameByIndexException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Aopen throws this exception on any error condition.
   ///</summary>
   public ref class H5AopenException : public HDFException
   {
     internal:
        H5AopenException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5LgetInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5LgetInfoException : public HDFException
   {
     internal:
        H5LgetInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DgetStorageSize throws this exception on any error condition.
   ///</summary>
   public ref class H5DgetCreatePropertyListException : public HDFException
   {
     internal:
        H5DgetCreatePropertyListException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DgetStorageSize throws this exception on any error condition.
   ///</summary>
   public ref class H5DgetStorageSizeException : public HDFException
   {
     internal:
        H5DgetStorageSizeException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5DvlenReclaim throws this exception on any error condition.
   ///</summary>
   public ref class H5DvlenReclaimException : public HDFException
   {
     internal:
        H5DvlenReclaimException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5OgetInfoByName throws this exception on any error condition.
   ///</summary>
   public ref class H5OgetInfoByNameException : public HDFException
   {
     internal:
        H5OgetInfoByNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5GgetInfoByName throws this exception on any error condition.
   ///</summary>
   public ref class H5GgetInfoByNameException : public HDFException
   {
     internal:
        H5GgetInfoByNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AopenByName throws this exception on any error condition.
   ///</summary>
   public ref class H5AopenByNameException : public HDFException
   {
     internal:
        H5AopenByNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AcreateByName throws this exception on any error condition.
   ///</summary>
   public ref class H5AcreateByNameException : public HDFException
   {
     internal:
        H5AcreateByNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5AdeleteByName throws this exception on any error condition.
   ///</summary>
   public ref class H5AdeleteByNameException : public HDFException
   {
     internal:
        H5AdeleteByNameException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TenumNameOf throws this exception on any error condition.
   ///</summary>
   public ref class H5TenumNameOfException : public HDFException
   {
     internal:
        H5TenumNameOfException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TenumValueOf throws this exception on any error condition.
   ///</summary>
   public ref class H5TenumValueOfException : public HDFException
   {
     internal:
        H5TenumValueOfException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberValue throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberValueException : public HDFException
   {
     internal:
        H5TgetMemberValueException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetOffset throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetOffsetException : public HDFException
   {
     internal:
        H5TgetOffsetException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetPrecision throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetPrecisionException : public HDFException
   {
     internal:
        H5TgetPrecisionException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetNorm throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetNormException : public HDFException
   {
     internal:
        H5TgetNormException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetMemberOffset throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetMemberOffsetException : public HDFException
   {
     internal:
        H5TgetMemberOffsetException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TgetFields throws this exception on any error condition.
   ///</summary>
   public ref class H5TgetFieldsException : public HDFException
   {
     internal:
        H5TgetFieldsException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PsetBuffer throws this exception on any error condition.
   ///</summary>
   public ref class H5PsetBufferException : public HDFException
   {
     internal:
        H5PsetBufferException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5PsetVlenMemManager throws this exception on any error condition.
   ///</summary>
   public ref class H5PsetVlenMemManagerException : public HDFException
   {
     internal:
        H5PsetVlenMemManagerException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TBgetTableInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5TBgetTableInfoException : public HDFException
   {
     internal:
        H5TBgetTableInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5TBgetFieldInfo throws this exception on any error condition.
   ///</summary>
   public ref class H5TBgetFieldInfoException : public HDFException
   {
     internal:
        H5TBgetFieldInfoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5EsetAuto throws this exception on any error condition.
   ///</summary>
   public ref class H5EsetAutoException : public HDFException
   {
     internal:
        H5EsetAutoException(System::String^ message, int errorCode);
   };

   ///<summary>
   /// H5Array throws this exception on any error condition.
   ///</summary>
   public ref class H5ArrayException : public HDFException
   {
     internal:
        H5ArrayException(System::String^ message, int errorCode);
   };

} // close namespace
