//This file is automatically generated - do not directly modify.

#include "HDFExceptionSubclasses.h"

using namespace System;

namespace HDF5DotNet
{ 
   H5DcreateException::H5DcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DopenException::H5DopenException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DcloseException::H5DcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DreadException::H5DreadException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DwriteException::H5DwriteException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetSpaceException::H5DgetSpaceException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetTypeException::H5DgetTypeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DsetExtentException::H5DsetExtentException(String^ message,
                                         int errorCode) :
      HDFException(message, errorCode)
   {
   }

   H5FcreateException::H5FcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5FcloseException::H5FcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5FopenException::H5FopenException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GcreateException::H5GcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GopenException::H5GopenException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetObjInfoException::H5GgetObjInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GIterateException::H5GIterateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GcloseException::H5GcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScreateSimpleException::H5ScreateSimpleException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScreateException::H5ScreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentDimsException::H5SgetSimpleExtentDimsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScloseException::H5ScloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcopyException::H5TcopyException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TsetSizeException::H5TsetSizeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcloseException::H5TcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetSizeException::H5TgetSizeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TsetOrderException::H5TsetOrderException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TopenException::H5TopenException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TinsertException::H5TinsertException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumCreateException::H5TenumCreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumInsertException::H5TenumInsertException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNativeTypeException::H5TgetNativeTypeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TvlenCreateException::H5TvlenCreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetClassException::H5TgetClassException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetSignException::H5TgetSignException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberNameException::H5TgetMemberNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberClassException::H5TgetMemberClassException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberIndexException::H5TgetMemberIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberTypeException::H5TgetMemberTypeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcreateException::H5TcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNMembersException::H5TgetNMembersException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectStridedHyperslabException::H5SselectStridedHyperslabException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectHyperslabException::H5SselectHyperslabException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentMaxDimsException::H5SgetSimpleExtentMaxDimsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentNDimsException::H5SgetSimpleExtentNDimsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentNPointsException::H5SgetSimpleExtentNPointsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectNoneException::H5SselectNoneException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetNumObjectsException::H5GgetNumObjectsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetObjectNameByIndexException::H5GgetObjectNameByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5EsuppressPrintingException::H5EsuppressPrintingException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcommitException::H5TcommitException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AcreateException::H5AcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AwriteException::H5AwriteException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AreadException::H5AreadException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AcloseException::H5AcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetNameException::H5AgetNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AopenNameException::H5AopenNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetSpaceException::H5AgetSpaceException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetTypeException::H5AgetTypeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetNumberOfAttributesException::H5AgetNumberOfAttributesException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AiterateException::H5AiterateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ADeleteException::H5ADeleteException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PcreateException::H5PcreateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PcloseException::H5PcloseException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PgetChunkException::H5PgetChunkException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PsetChunkException::H5PsetChunkException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PsetDeflateException::H5PsetDeflateException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TisVariableStringException::H5TisVariableStringException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5OgetInfoByIndexException::H5OgetInfoByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5LgetInfoByIndexException::H5LgetInfoByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetNameByIndexException::H5AgetNameByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AopenIndexException::H5AopenIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AopenByIndexException::H5AopenByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AgetInfoException::H5AgetInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5OgetInfoException::H5OgetInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetInfoException::H5GgetInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5LgetNameByIndexException::H5LgetNameByIndexException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AopenException::H5AopenException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5LgetInfoException::H5LgetInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetCreatePropertyListException::H5DgetCreatePropertyListException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetStorageSizeException::H5DgetStorageSizeException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DvlenReclaimException::H5DvlenReclaimException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5OgetInfoByNameException::H5OgetInfoByNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetInfoByNameException::H5GgetInfoByNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AopenByNameException::H5AopenByNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AcreateByNameException::H5AcreateByNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5AdeleteByNameException::H5AdeleteByNameException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumNameOfException::H5TenumNameOfException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumValueOfException::H5TenumValueOfException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberValueException::H5TgetMemberValueException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetOffsetException::H5TgetOffsetException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetPrecisionException::H5TgetPrecisionException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNormException::H5TgetNormException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberOffsetException::H5TgetMemberOffsetException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetFieldsException::H5TgetFieldsException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PsetBufferException::H5PsetBufferException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PgetLayoutException::H5PgetLayoutException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5PsetVlenMemManagerException::H5PsetVlenMemManagerException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TBgetTableInfoException::H5TBgetTableInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TBgetFieldInfoException::H5TBgetFieldInfoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5EsetAutoException::H5EsetAutoException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ArrayException::H5ArrayException(String^ message,
                                         int errorCode) : 
      HDFException(message, errorCode)
   {
   }

} // close namespace
